name: Run Cypress Tests Daily

on:
  schedule:
    # Runs at 10:00 AM UTC every day
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Replace with your required Node.js version

      - name: Install dependencies
        run: npm install  # or yarn install if you're using Yarn

      - name: Run Cypress tests
        run: npx cypress run  # or npm run cypress run if you have a script defined
