name: Run Cypress Tests Daily

on:
  schedule:
    # Runs at 10:00 AM UTC every day
    - cron: '15 16 * * *'
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Cypress Tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: 'fedd668a-3caa-41ff-b13d-083325f6993e'
